name: "Pull Requests"
run-name: "PR | ${{ github.head_ref }} --> ${{ github.base_ref }} | ${{ github.event.pull_request.title }}"

on: pull_request

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Setup Golang"
        uses: actions/setup-go@v4.0.1
        with:
          go-version: '1.20'

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: "Install pre-commit dependencies"
        run: |
          go version
          go install github.com/mgechev/revive@v1.3.2
          go install github.com/securego/gosec/v2/cmd/gosec@v2.16.0
          go install honnef.co/go/tools/cmd/staticcheck@v0.4.3
          go install mvdan.cc/gofumpt@v0.5.0
          go install golang.org/x/tools/cmd/goimports@latest
          go install -v github.com/go-critic/go-critic/cmd/gocritic@v0.8.1
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      - name: "Run pre-commit checks"
        uses: pre-commit/action@v3.0.0

      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
